### ISSUE TITLE
Zugriffsrechte Leo Müller

### ISSUE THREAD

**Issue by thomashaensli** [gtadigital/experimentaldesign-datacuration#3]
Leo Müller arbeitet derzeit mit den Zugriffsrechten von Rainer Schützeichel, dies sollte korrigiert werden, vgl. https://github.com/gtadigital/experimentaldesign-datacuration/wiki/9-Notes

**Comment by thomashaensli** [comment]
Gruppenzuteilung an diejenige von R. Schützeichel angepasst  13.2.2023

<img width="2532" alt="Bildschirmfoto 2023-02-13 um 11 21 59" src="https://user-images.githubusercontent.com/30504518/219393399-c2539514-693e-41c5-a948-4cc5917dca8a.png">

**Comment by thomashaensli** [comment]
Mail 15.2.23, 15.07:

> Lieber Thomas,
> 
> ich arbeite noch immer in dem Konto von Rainer, da mir noch nicht die Berechtigung erteilt wurde, um im Oeuvre zu arbeiten. Nun inzwischen wird es dringend, dass ich mit meinen eigenen Zugangsdaten arbeiten kann, da ich seit unserer Besprechung am [Montag](http://airmail.calendar/2023-02-20%2012:00:00%20MEZ) mit meiner Arbeit voranschreite.
> 
> Ich meine mich zu erinnern, dass die Rede davon war, dass ich in der Archiv-Gruppe aufgenommen werde. Ich bitte dich höflichst, mir die Berechtigung zu erteilen.
> 
> Vielen Dank im Voraus.
> Mit freundlichen Grüßen
> _
> 
> Leo Müller
> MSc. ETH Arch.

**Comment by thomashaensli** [comment]
Lieber Leo, 
Deine Zugriffrechte haben wir letzten Montag im Meeting unmittelbar angepasst.  Ggf. musst Du Dich neu einloggen. 

LG Thomas

**Comment by leomueller2161** [comment]
Lieber Thomas,

Ich bin heute nicht am HIL. Könnte ich morgen vorbei kommen?

Das problem ist, dass mir keine Ergebnisse im Oeuvre angezeigt werden.

<img width="1790" alt="grafik" src="https://user-images.githubusercontent.com/73562725/219409319-92229ccb-0109-4d5c-af56-d14b2cd5dd79.png">


Liebe Grüße,
_

Leo Müller
MSc. ETH Arch. 

T: +41 (0) 76 232 0 131
muller@arch.ethz.ch

**Comment by thomashaensli** [comment]
HI @leomueller2161 

danke für die schnelle Rückmeldung (un die Anmeldung bei Github, klappt perfekt). 

Lass und schnell ein paar mögliche Ursachen ausschliessen und so das Problem eingrenzen: 

a) bei den `Resourcen`sind bei Dir 2 Pools angewählt. Hier musst Du ggf. die Pools `gta Archiv` und `gta Isler? auswählen.  Ändert das was? 

Beste Grüsse, Th.

**Comment by thomashaensli** [comment]
Nachtrag zu 
> a) bei den `Resourcen`sind bei Dir 2 Pools angewählt. Hier musst Du ggf. die Pools `gta Archiv` und `gta Isler` auswählen.

Das müsste dann so aussehen, @leomueller2161 : 

![Bildschirmfoto 2023-02-16 um 16 41 51](https://user-images.githubusercontent.com/30504518/219415046-be72f7ec-d782-4317-9f08-a82aa5d1597f.png)

**Comment by thomashaensli** [comment]
@leomueller2161 kann Du mir hier noch schnell eine Rückmeldung geben? Klappt es jetzt?

**Comment by leomueller2161** [comment]
Lieber Thomas,

Ich habe nicht gesehen, dass du mir hier geantwortet hast. 
Ich habe inzwischen noch mal geprüft, ob das die Ursache des Problems ist, und ich kann bestätigen, dass mir nun die Einträge angezeigt werden.

Vielen dank und
liebe Grüße,

Leo

**Comment by thomashaensli** [comment]
Lieber Leo, 

cool, super. Dann schliesse ich diesen Issue. ich bin morgen wieder im HIL, falls du weitere Fragen hast. 
Herzlich, Thomas
