### ISSUE TITLE
Gelber "Verify"-Tag

### ISSUE THREAD

**Issue by leomueller2161** [gtadigital/experimentaldesign-datacuration#7]
Lieber Thomas,

Es gibt im CMS einen gelben "Verify"-Tag der verschwindet, sobald man den Eintrag bearbeitet. Er ist, soweit ich es erkennen kann, auch nicht mehr unter den Tags zu finden. Ich vermute, dass dieser Tag nicht mehr relevant ist, vermutlich sogar garncht mehr existiert - ist diese Annahme richtig? Wie behandele ich am besten diese Projekte?

Liebe Grüße,
Leo

**Comment by vinegar-ethz** [comment]
Du kannst ihn entfernen.

**Comment by thomashaensli** [comment]
Blocker von #12 

Resolves in #13

**Comment by thomashaensli** [comment]
Resolves in #13
